export const CHANGE_STEP = "CHANGE_STEP";

export const UPDATE_DETAILS = "UPDATE_DETAILS";

export const UPDATE_DETAILS_FIRSTNAME = "UPDATE_DETAILS_FIRSTNAME";

export const UPDATE_DETAILS_LASTNAME = "UPDATE_DETAILS_LASTNAME";

export const UPDATE_DETAILS_EMAIL = "UPDATE_DETAILS_EMAIL";

export const UPDATE_DETAILS_PASSWORD = "UPDATE_DETAILS_PASSWORD";

export const UPDATE_DETAILS_PHONE = "UPDATE_DETAILS_PHONE";

export const UPDATE_DETAILS_ALTERNATE = "UPDATE_DETAILS_ALTERNATE";
